### ISSUE TITLE
Edit lint script so it will lint JS and CSS sequentially

### ISSUE THREAD

**Issue by Jesus-Gonzalez** [jferrettiboke/universal-react-boilerplate#1]
As I can see, the NPM `lint` script is linting JS _only if_ `lint:css` script _exit code_ is successful. In my opinion it should run sequentially/independently, so I will create a pull request in order to "fix" this.

In practice, if you run `npm run lint` and there are any CSS errors, it will not lint JS. I think it should also lint the JS files.

**Comment by jferrettiboke** [comment]
It is good stopping the process if there is an error. We can save time and being more productive developers.

Imagine, if you have a CSS syntax error and more than 100 success tests, the time matters. So, it will be better if the process can stopping right there to show you the CSS errors and not continue executing all your success tests.

Anyway, big thank you for your first contribution to this project.
